version: 3
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
