version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    groups:
      python-workflows:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    groups:
      python-docs:
        patterns:
          - ."*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    groups:
      python:
        patterns:
          - "*"