version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 100
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 100
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 100
